# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery Section
  description: Gallery Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: gallery
  button:
    text: SEE MORE
  gallery:
    - image: /images/gallery-1.png
      image_alt: alt text
    - image: /images/gallery-2.png
      image_alt: alt text
    - image: /images/gallery-3.png
      image_alt: alt text
    - image: /images/gallery-4.png
      image_alt: alt text
    - image: /images/gallery-5.png
      image_alt: alt text
    - image: /images/gallery-6.png
      image_alt: alt text
    - image: /images/gallery-1.png
      image_alt: alt text
    - image: /images/gallery-2.png
      image_alt: alt text
    - image: /images/gallery-3.png
      image_alt: alt text
    - image: /images/gallery-4.png
      image_alt: alt text
    - image: /images/gallery-5.png
      image_alt: alt text
    - image: /images/gallery-6.png
      image_alt: alt text
    - image: /images/gallery-1.png
      image_alt: alt text
    - image: /images/gallery-2.png
      image_alt: alt text
    - image: /images/gallery-3.png
      image_alt: alt text
    - image: /images/gallery-4.png
      image_alt: alt text
    - image: /images/gallery-5.png
      image_alt: alt text
    - image: /images/gallery-6.png
      image_alt: alt text
    - image: /images/gallery-1.png
      image_alt: alt text
    - image: /images/gallery-2.png
      image_alt: alt text
    - image: /images/gallery-3.png
      image_alt: alt text
    - image: /images/gallery-4.png
      image_alt: alt text
    - image: /images/gallery-5.png
      image_alt: alt text
    - image: /images/gallery-6.png
      image_alt: alt text

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  button[*].text:
    label: text button
    type: text
  gallery[*].image:
    label: image
    type: image
  gallery[*].image_alt:
    label: image alt
    type: text
