# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Banner Booking Section
  description: Banner Booking Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  background: "#000"
  banner: /images/banner.png
  banner_alt: /images/banner.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  banner:
    label: image
    type: image
  banner_alt:
    label: alt image
    type: text
  background:
    label: background
    type: color
