# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Section
  description: Contact Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  background: "#000"
  text_color: "#fff"
  background_box: "#fff"
  contact:
    - icon: /images/location.png
      value: 11011 Richmond Ave, Ste 900, Houston, TX 77042
    - icon: /images/headphone.png
      value: 832-968-6668
    - icon: /images/sms.png
      value: contact@fastboy.net

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  banner:
    label: image
    type: image
  text_color:
    label: text color
    type: color
  background:
    label: background
    type: color
  background_box:
    label: background
    type: color
  contact[*].icon:
    label: Icon image
    type: image
  contact[*].value:
    label: Value contact
    type: text

