# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Map Booking Section
  description: Map Booking Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  background: "#000"
  map: <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1732.3539319042645!2d-95.57140404415983!3d29.72822039379335!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640ddc6ed681049%3A0x74ace03ed50728e8!2sFastboy%20Marketing%20%26%20Construction!5e0!3m2!1svi!2s!4v1704442145710!5m2!1svi!2s" width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  map:
    label: map
    type: markdown
  background:
    label: background
    type: color
